### ISSUE TITLE
Failure: Project Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.

### ISSUE THREAD

**Issue by prediatorr** [kentcdodds/react-fundamentals#1]
Running the following command: npm run validate --if-present -s
'react\react\react-fundamentals\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'D:\npm-run-all\bin\npm-run-all\index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by kentcdodds** [comment]
Hello @prediatorr!

This is very odd. It looks like you have some issues on your system with your install of dependencies. Could you try again? Please make sure to run `npm run setup` first.

**Comment by prediatorr** [comment]
> Hello @prediatorr!
> 
> This is very odd. It looks like you have some issues on your system with your install of dependencies. Could you try again? Please make sure to run `npm run setup` first.

This is not installing properly all vite apps

**Comment by kentcdodds** [comment]
Hi @prediatorr,

This is not a vite app. It sounds like you've got something wrong with your computer. It's very strange that npm seems to be looking for a module at the location `D:\npm-run-all\bin\npm-run-all\index.js`. I'm sorry it's not working for you. I'm afraid there's nothing I can do. I hope you get things worked out.

**Comment by prediatorr** [comment]
Reinstalling nodejs helped me. Anyways thank you for the responses.

**Comment by kentcdodds** [comment]
That makes sense. I'm glad you got it working!
