### ISSUE TITLE
Can't install node modules

### ISSUE THREAD

**Issue by codeepic** [kentcdodds/react-fundamentals#103]
The `node setup` command doesn't work for me. Not a biggie, since I thought I could just run `npm install` and start the app running `npm start`. Not luck either.

I restarted the computer, removed and cloned again `react-fundamentals` repo.
Have run `npm cache clean` and `npm cache verify`.

Finally I get to run `npm install` and this is what I see:

![image](https://user-images.githubusercontent.com/6895033/95734425-59152200-0c7b-11eb-8435-a35c0a3ae954.png)

Any ideas before I start going deeper into the rabbit hole?

git v:         2.22
node v:     12.7.0
npm v:      6.10

**Comment by codeepic** [comment]
Ok - solved - when you see this problem after you just cloned the repo - first remove `package-lock.json` an then run `npm install` and after 'npm run start' to start the app.

**Comment by kentcdodds** [comment]
Glad you got it fixed. Just noticed you're running within a dropbox folder. I strongly advise against this, otherwise: https://medium.com/@bozzified/solving-painful-syncing-of-node-modules-when-using-dropbox-or-google-drive-a77c2ab0c97c

Good luck!

**Comment by codeepic** [comment]
Thanks for the link Kent. I've been using Dropbox for syncing between computers (not all my sandbox and pet projects are uploaded to github) to be able to switch between work and multiple personal laptops without skipping a beat or when also working with large files (Photoshop, Blender, Unity 3D game assets) and I never had a problem with node_modules.
