### ISSUE TITLE
Double clicking "Complete and Continue" doesn't mark step as done

### ISSUE THREAD

**Issue by idbartosz** [kentcdodds/react-fundamentals#107]
This issue is related to the course app rather than content but I wasn't sure where to leave this feedback 📦

**Steps to reproduce:**

1. Click "complete and continue"
2. Immediately after step one click the green checkmark

**Expected behavior:**

a. Step should be marked as done in the right panel no matter how many times we click
b. In case it's an expected "undo" behavior then it should be signaled a bit differently and/or debounced to prevent accidental double clicks 😉

**Browser:**

Chrome: 86.0.4240.75 (Official Build) (x86_64)

**Screenshot:**

![2020-10-14 21-47-13 2020-10-14 21_48_56](https://user-images.githubusercontent.com/21260478/96038965-3bf17680-0e68-11eb-9510-f63734f07473.gif)

**Comment by kentcdodds** [comment]
Thanks for letting us know. I've reported this to the team.
