### ISSUE TITLE
Error Code 1

### ISSUE THREAD

**Issue by Tboules** [kentcdodds/react-fundamentals#108]
When I run "npm run setup --silent" I get the following error. 

npm ERR! code 1
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tboul\AppData\Roaming\npm-cache\_logs\2020-10-19T21_14_48_952Z-debug.log
Install for [ 'git+https://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git' ] failed with code 1

what should I do?

**Comment by kentcdodds** [comment]
Hi @Tboules!

This is a common issue for windows-based setups. You could check #105 and try to get that fixed, or simply skip the system validation step and run the setup manually:

```
npm install
npm run validate
```

**Comment by Tboules** [comment]
Thanks, that worked!
