### ISSUE TITLE
test is not working

### ISSUE THREAD

**Issue by JaredBed88** [kentcdodds/react-fundamentals#11]
<img width="943" alt="Screen Shot 2020-03-24 at 8 46 40 AM" src="https://user-images.githubusercontent.com/56315662/77450602-bb2a3a80-6db0-11ea-8d10-768893ea9336.png">

**Comment by kentcdodds** [comment]
It looks like you're not in the project directory:

```
cd react-fundamentals
npm test
```

That should work :)

**Comment by kentcdodds** [comment]
Let me know if it doesn't :)

**Comment by JaredBed88** [comment]
amazing thank you
