### ISSUE TITLE
Can only access the first module the rest doesn't play

### ISSUE THREAD

**Issue by rkristelijn** [kentcdodds/react-fundamentals#11]
I've purchased the course, but only the first module plays video's. I've already mailed support to team@epicreact.dev at Thu 23-May-24 13:21 but no response yet.

![image](https://github.com/kentcdodds/react-fundamentals/assets/21142148/1d13baaa-4052-4cba-9590-3cfb8313ad97)

in the console I get these error:
Error: GraphQL Error (Code: 404): {"response":{"message":"Resource Not Found","error":true,"not_found":true,"status":404},"request":{"query":"\n  query LessonData($slug: String!) {\n    video_resource(slug: $slug) {\n      slug\n      subtitles_url\n      lesson_view_url\n      dash_url\n      hls_url\n    }\n  }\n","variables":{"slug":"egghead-er-01-01-01-basic-js-hello-world-intro"}}}

**Comment by kentcdodds** [comment]
It's possible there was a system hiccup when you tried. Could you try it again. It's working for me now.

**Comment by rkristelijn** [comment]
I tried over the course of several days, just tried it again, nothing changes, what should I investigate?

**Comment by rkristelijn** [comment]
I tried cleaning cache, logout, login; same issue

![image](https://github.com/kentcdodds/react-fundamentals/assets/21142148/9fb25075-634c-4a01-a85c-18885fb80e4f)

It says 'logout' so I'm assuming I'm logged in

**Comment by kentcdodds** [comment]
I'm sorry you're having these issues. Unfortunately because I and my team can't reproduce the issues there's little we can do. I can only assume there's an issue with the network you're using or your machine.

**Comment by kentcdodds** [comment]
Ah! I take it back. It looks like my team was able to reproduce the issue when signed in as you and they're looking into it!

**Comment by kentcdodds** [comment]
This should be resolved now. Let me know if it is not.

**Comment by rkristelijn** [comment]
It was resolved @kentcdodds thanks 🙏
