### ISSUE TITLE
npm run setup --silent AND npm start silently fail on Mac

### ISSUE THREAD

**Issue by pranavambwani** [kentcdodds/react-fundamentals#113]
I meet the system requirements:
- git v2 or greater (2.21.0)
- NodeJS v10 or greater (v14.14.0)
- npm v6 or greater (6.14.8)

However, the commands `npm run setup --silent` and `npm start` silently fail (see below).

![issue](https://user-images.githubusercontent.com/68523364/96962247-68df0280-14d4-11eb-9516-8f83f733f688.gif)

I've tried to delete the repository completely from my machine and start it all over again, but no luck. Any idea what might be happening?

**Comment by kentcdodds** [comment]
The fact you get no output whatsoever is very odd... Does npm work for you in other projects?

If you need to get unstuck, checkout the alternatives to running locally in the README

**Comment by pranavambwani** [comment]
`npm` works for all other projects. I'll check out the alternatives to running locally.

**Comment by deshiknaves** [comment]
For anyone else who has this issue. I saw this issue on someone else's computer and it turns out there is something wrong with `npm` itself. Running `node setup` works fine. Using `yarn run setup` works fine.

**Comment by deshiknaves** [comment]
https://stackoverflow.com/questions/59016328/npm-run-doesnt-do-anything
