### ISSUE TITLE
Incorrect link when trying to edit the markdown docs

### ISSUE THREAD

**Issue by KarelVerschraegen** [kentcdodds/react-fundamentals#117]
# Incorrect Redirect

When trying to edit the docs in the React-fundamentals workshop, the pencil redirects to 
> https://github.com/kentcdodds/react-workshop-app/edit/main/src/exercise/06.md 

instead of 

> https://github.com/kentcdodds/react-fundamentals/edit/main/src/exercise/06.md

## How to replicate
1. Run `yarn start`
2. Go to excercise 6 (or any other excercise)
3. Click on the edit pencil
4. See the Github 404 page.

**Comment by kentcdodds** [comment]
@KarelVerschraegen, this was a problem a while ago, but if you do a `git pull` and reinstall dependencies then it should be fixed. Thanks!
