### ISSUE TITLE
Font is not visible on the speed controls of the video in light mode

### ISSUE THREAD

**Issue by rimildeyjsr** [kentcdodds/react-fundamentals#118]
The font is not visible on the speed controls of the video in light mode - attached a screenshot for it!

![Screenshot 2020-10-26 at 7 16 35 PM](https://user-images.githubusercontent.com/10229595/97180185-beaaf780-17bf-11eb-90e5-8df0328c5f88.png)

**Comment by kentcdodds** [comment]
cc @dealingwith :)

**Comment by kentcdodds** [comment]
This has been fixed

**Comment by rimildeyjsr** [comment]
Thanks @kentcdodds :)
