### ISSUE TITLE
Error when running npm start or npm run validate

### ISSUE THREAD

**Issue by nickytonline** [kentcdodds/react-fundamentals#121]
Hi Kent, I was up and running fine initially with the react fundamentals on my local, but this evening I restarted things after having done a `git clean -dfx`.

The error I'm getting is 

```bash
Failed to compile.

./src/index.js
Error: /Users/nickytonline/dev/react-fundamentals/src/index.js: codegen.macro: Cannot find a repository URL for this workshop. Check that the package.json at "/Users/nickytonline/dev/react-fundamentals/package.json" has {"repository": {"url": "this should be set to a github URL"}} Learn more: https://www.npmjs.com/package/codegen.macro
    at Array.forEach (<anonymous>)
```

The error says exactly what is wrong so I added this to the package.json of the project and then everything worked fine.

```json
  "repository": {
    "url": "https://github.com/kentcdodds/react-fundamentals"
  },
```

No idea why this started happening after a clean install.

**Comment by kentcdodds** [comment]
This was missing in the past, but it's been added now. Thanks!
