### ISSUE TITLE
System validation failure over Node 15

### ISSUE THREAD

**Issue by smhmd** [kentcdodds/react-fundamentals#123]
I could use `nvm`, though.
![image](https://user-images.githubusercontent.com/46059092/98789200-46207980-2402-11eb-8e9a-4d30e6499d4d.png)

**Comment by kentcdodds** [comment]
Yep, this is intentional. Node 15 is not LTS so I don't want to work about supporting it. Please downgrade to an LTS version of node.

Thanks!
