### ISSUE TITLE
I don't see the "Extra Credit" tab.

### ISSUE THREAD

**Issue by tr1s** [kentcdodds/react-fundamentals#138]
Did this get removed at some point?

I just cloned the project today and am noticing that the follow along videos have a "Extra Credit" tab, and my local version doesn't show that for any of the sections:

<img width="471" alt="CleanShot 2020-11-30 at 20 35 23@2x" src="https://user-images.githubusercontent.com/19172250/100686306-0f2bec80-334c-11eb-801a-d6e66bb383ba.png">

**Comment by kentcdodds** [comment]
It's now part of the final tab.

**Comment by tr1s** [comment]
> It's now part of the final tab.

Okay thanks for the quick answer!
