### ISSUE TITLE
Having issue with building and starting the project

### ISSUE THREAD

**Issue by Nitin2392** [kentcdodds/react-fundamentals#158]
I just started the course and was able to `clone and setup` the project locally. I was having issues with running `node setup` because there is a space between my firstname and lastname and `npx` wasn't liking that. I was able to fix that but there seems to be another issue now when I run `npm run build` or `npm start`. 

```
C:/Users/Nitin Rangarajan/source/repos/EpicReact/react-fundamentals/src/exercise/01.md (C:/Users/Nitin Rangarajan/source/repos/EpicReact/react-fundamentals/node_modules/babel-loader/lib!C:/Users/Nitin Ran

SyntaxError: C:\Users\Nitin Rangarajan\source\repos\EpicReact\react-fundamentals\src\exercise\01.md: Support for the experimental syntax 'jsx' isn't currently enabled (18:10):

  16 |   ...props
  17 | }) {
> 18 |   return <MDXLayout {...layoutProps} {...props} components={components} mdxType="MDXLayout">
     |          ^
  19 |     <h1 {...{
  20 |       "id": "basic-javascript-rendered-hello-world"
  21 |     }}>{`Basic JavaScript-rendered Hello World`}</h1>

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
```

**Comment by Nitin2392** [comment]
I did some googling and found that this issue can be fixed by changing the `"main"` section in `package.json` to the follows: 

Change from 
`"main": "/src/index.js",`
to
`"main": "./build/src/index.js",`

because Webpack will resolve to the untranspiled JSX source.

I am going to leave this issue open to confirm if this is the right approach to solve this problem.

**Comment by kentcdodds** [comment]
Hi @Nitin2392,

This is strange. Did the installation step of the `setup` script not work for you?

In your suggestion, are you talking about [this package.json main property](https://github.com/kentcdodds/react-fundamentals/blob/01f88d84505db006ea248cbfcdbe5f780920eb0c/package.json#L9)? Because `./build/src/index.js` doesn't exist so I'm not sure how this could fix anything 🤔

**Comment by Nitin2392** [comment]
Hey @kentcdodds! The installation step of the `setup` didn't work for me at first but that was due to a `npx` error with a space existing between my First and Last names in the `C/User/{name}` folder path. 

The `setup` script did not throw this `babel` error! Hmm, interesting that this fix worked for me!

**Comment by kentcdodds** [comment]
Hmmm... Yeah, this is odd. We can keep this issue around in case it helps anyone else, but I don't think there's much we can do about it from now so I'll close it. Thanks!
