### ISSUE TITLE
Invalid link syntax on React Fundamentals Welcome webpage

### ISSUE THREAD

**Issue by jstheoriginal** [kentcdodds/react-fundamentals#168]
Hi!

Note: I couldn't find a way to do a pull request to fix source code on the website itself.

The links to the PATH fixes paragraph [here](https://epicreact.dev/modules/react-fundamentals/react-fundamentals-welcome) aren't valid syntax. The same links in this README in this repo are valid.

```
If you have trouble with any of these, learn more about the PATH environment variable and how to fix it here for [windows][win-path] or [mac/linux][mac-path].
```

Edit: The link for requesting help by filing an issue is also invalid on the same page:

```
If you get any errors, please read through them and see if you can find out what the problem is. If you can't work it out on your own then please [file an issue][issue] and provide all the output from the commands you ran (even if it's a lot).
```

Thanks!

**Comment by kentcdodds** [comment]
Cc @dealingwith

**Comment by kentcdodds** [comment]
We'll get that fixed. Thanks @jstheoriginal!
