### ISSUE TITLE
Tip: Set prettierrc to semi: true

### ISSUE THREAD

**Issue by las3r** [kentcdodds/react-fundamentals#195]
A quick tip as I'm running through the first excersizes of epicreact.

Code syntax highlighting is broken for me when using the default prettierrc, as semi is set to false. I'm not sure if this is your preference, but as you can see on the "Generate DOM Nodes"-Solution video, you see that the syntax highlighting is broken because of the missing semicolons. It was confusing to me as I'm simply used to `no colors = I did something wrong`.

Hopefully these tips are welcome

**Comment by kentcdodds** [comment]
The tips are definitely welcome.

I'm aware of the syntax highlighting issues with semicolonless-js-in-html 😅 It's annoying, but no-semi is definitely my preference.
