### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by SuperGent** [kentcdodds/react-fundamentals#196]
I can't start anything as the validation doesn't work.

Output:
--------
D:\Code\EpicReact\react-fundamentals>npm run setup --silent
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
    🚨  Failure: System Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.

D:\Code\EpicReact\react-fundamentals>npm --version
7.20.0

D:\Code\EpicReact\react-fundamentals>node --version
v14.17.3

D:\Code\EpicReact\react-fundamentals>git --version
git version 2.14.1.windows.1

**Comment by kentcdodds** [comment]
Hi @SuperGent,

I'm afraid there's not enough in that output for me to advise you. Have you tried the alternatives mentioned in the README of this project?

**Comment by jadetruexo** [comment]
I am receiving the same issue, @SuperGent did you manage to resolve this?

I've tried the following commands:

```
npm install
npm run validate
```


```
PS C:\Users\Me\Documents\epic_react\react-fundamentals> npm run setup --silent
 ▶️  Starting workshop setup...
       Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
     ▶️  Starting: System Validation
           Ensuring the correct versions of tools are installed on this computer.
           Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
     🚨  Failure: System Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.
```

**Comment by kentcdodds** [comment]
Hi @jadetruexo,

Unfortunately there's not enough output for me to know what the problem is. Have you tried the alternatives mentioned in the README of this project?

**Comment by SuperGent** [comment]
I did manage to get t going, I think I just installed everything manually, and ignored the auto install scripts.
As you said @kentcdodds there isn't any error messages coming back from that script so it's impossible to debug.
This shows me that I need to learn a good deal more about Node, NPM, JS, etc before I can embark on this course.
