### ISSUE TITLE
Inconsistent System Requirements

### ISSUE THREAD

**Issue by samanthablasbalg** [kentcdodds/react-fundamentals#197]
The System Requirements listed in the workshop say:

```
System Requirements
git v2 or greater
NodeJS v10 or greater
npm v6 or greater
```

However, when I was trying to install the repo, it gave me this error:

```
npx: installed 2 in 2.51s
There were errors validating the compatibility of this computer:

    This computer has node@v10.13.0 installed, but node@12 || 14 || 15 || 16 is required. Please update node: https://nodejs.org


If you would like to just ignore this error, then feel free to do so and install dependencies as you normally would in "/Users/samanthablasbalg/repos/epicreact/react-fundamentals". Just know that things may not work properly if you do...
    🚨  Failure: System Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.
```

This was resolved by upgrading Node, but I would have done that earlier if the System Requirements had an up to date version requirement.

**Comment by kentcdodds** [comment]
Hi @samanthablasbalg,

Thanks for letting me know. Can you tell me where you read those system requirements so I can get it updated. The repo README itself has the right system requirements listed.

**Comment by samanthablasbalg** [comment]
Hi @kentcdodds , it is in the actual workshop site! I admittedly didn't think to look at the repo itself, I was following the instructions here and juts cloned without going to the repo site directly:

https://epicreact.dev/modules/react-fundamentals/react-fundamentals-welcome

**Comment by kentcdodds** [comment]
@zacjones93, could you look into getting this fixed?

Thanks @samanthablasbalg!
