### ISSUE TITLE
Issue with Extra Credit Tab on Exercises

### ISSUE THREAD

**Issue by Hetzendorfer** [kentcdodds/react-fundamentals#198]
There is no Extra Credit Tab like in the video "Running the Epic React Wordkshop App" and the margin above and under the pre Elements is not there like in the video

**Comment by kentcdodds** [comment]
Hi @Hetzendorfer!

The app has changed a bit since the recording to make things easier to follow for every exercise. You'll find the extra credits under the "final" tab now:

![image](https://user-images.githubusercontent.com/1500684/127546745-fc0a6333-449e-4146-b618-54dc50bfc872.png)

**Comment by johannao76** [comment]
@kentcdodds, I was unable to run the extra credit exercise after I finished it. I am able to open the isolated extra credit final page using this link: http://localhost:3000/isolated/final/01.extra-1.html, but when I change the link to http://localhost:3000/isolated/exercise/01.extra-1.html, I get this: 
![image](https://user-images.githubusercontent.com/11838969/209595652-391eb5fb-2e72-4210-817a-e35efbe08903.png)

**Comment by kentcdodds** [comment]
Hi @johannao76,

Did you create a new file to finish the extra credit? You're not intended to create new files yourself. You should only work within the files provided. Continue to work in the `exercise/01.html` file.
