### ISSUE TITLE
Installation problem in windows 

### ISSUE THREAD

**Issue by stanzin-hub** [kentcdodds/react-fundamentals#199]
Hii Kent recently i bought your Course epic react pro.. i am facing some problems of cloning git in windows powershell
It is showing this issue..

PS C:\epicreact> git clone https://github.com/kentcdodds/<module-name>.git react_fundamentals
Cloning into 'react_fundamentals'...
fatal: unable to access 'https://github.com/kentcdodds/<module-name>.git/': The requested URL returned error: 400

**Comment by kentcdodds** [comment]
Hi @stanzin-hub,

That URL is wrong. Try: `https://github.com/kentcdodds/react-fundamentals.git`

**Comment by stanzin-hub** [comment]
Hii@kentcdodds
Yeah my issue is now solved.
I am really enjoying your course..
Thank you..🙏
