### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by nikkii94** [kentcdodds/react-fundamentals#2]
Hello! I am getting errors during the dependency install:

`node setup
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx --yes "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"    ✅  Success: System Validation

    ▶️  Starting: Dependency Installation
          Installing third party code dependencies so the workshop works properly on this computer.
          Running the following command: npm install --legacy-peer-deps --no-save
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'D:\\sites\\react-fundamentals\\node_modules\\@cspotcode\\source-map-support',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\sites\react-fundamentals\node_modules\@cspotcode\source-map-support\node_modules'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\sites\\react-fundamentals\\node_modules\\@cspotcode\\source-map-support\\node_modules'npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'D:\\sites\\react-fundamentals\\node_modules\\@jridgewell\\source-map',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\sites\react-fundamentals\node_modules\@jridgewell\source-map\node_modules'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\sites\\react-fundamentals\\node_modules\\@jridgewell\\source-map\\node_modules'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'D:\\sites\\react-fundamentals\\node_modules\\eslint-plugin-react',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\sites\react-fundamentals\node_modules\eslint-plugin-react\node_modules\resolve\test\resolver\symlinked\_\symlink_target'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\sites\\react-fundamentals\\node_modules\\eslint-plugin-react\\node_modules\\resolve\\test\\resolver\\symlinked\\_\\symlink_target'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path D:\sites\react-fundamentals\node_modules\husky
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node husky install
npm ERR! node:internal/modules/cjs/loader:452
npm ERR!       throw err;
npm ERR!       ^
npm ERR!
npm ERR! Error: Cannot find module 'D:\sites\react-fundamentals\node_modules\please-upgrade-node\index.js'. Please verify that the package.json has a valid "main" entry
npm ERR!     at tryPackage (node:internal/modules/cjs/loader:444:19)
npm ERR!     at Module._findPath (node:internal/modules/cjs/loader:715:18)
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:985:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at Object.<anonymous> (D:\sites\react-fundamentals\node_modules\husky\husky.js:3:27)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   path: 'D:\\sites\\react-fundamentals\\node_modules\\please-upgrade-node\\package.json',
npm ERR!   requestPath: 'please-upgrade-node'
npm ERR! }
npm ERR!
npm ERR! Node.js v20.10.0

npm ERR! A complete log of this run can be found in: C:\Users\Niki\AppData\Local\npm-cache\_logs\2024-01-19T13_09_08_095Z-debug-0.log
    �  Failure: Dependency Installation. Please review the messages above for information on how to troubleshoot and re
solve this issue.
`

My node version is 
$ node -v
v20.10.0

npm install also throws these errors.

Thanks for the help!

**Comment by kentcdodds** [comment]
Hello @nikkii94, it looks like there's something wrong with the way node/npm are installed on your system. The `EPERM: operation not permitted, rmdir` error makes me think you have permissions issues.

The build for windows is passing so I'm thinking it is something wrong with your computer setup. Sorry I can't be more helpful than that! 😬
