### ISSUE TITLE
settings.kcd.json has a setting that doesn't exist

### ISSUE THREAD

**Issue by jaquinocode** [kentcdodds/react-fundamentals#218]
https://github.com/kentcdodds/react-fundamentals/blob/60cc5a99b82fd87499c61e0a6ac189f96020f41a/.vscode/settings.kcd.json#L18-L20

The lines of code above show a "USE_GITIGNORE" string that simply doesn't exist as a possible option. So vscode doesn't recognize it and this setting ends up doing nothing. These 3 lines of code should be deleted! (And someone should tell Kent to not use it anymore!)

Proof that it doesn't exist:
The `files.exclude` setting is supposed to hide files and folders in the sidebar Explorer. Therefore, the above setting should in theory hide `node_modules` (AKA don't show the folder at all) since it's in the .gitignore. But if you use the setting, you'll notice this doesn't happen and that it does nothing.
Also, no documentation of this exists anywhere. Kent, I think you incorrectly thought this [code here](https://github.com/microsoft/vscode/issues/78#issuecomment-164430983) was valid code but it was just a suggestion they were making. Hey, it happens!

**Comment by kentcdodds** [comment]
Just updated everything and I think we're good now. Thanks!
