### ISSUE TITLE
node 17 open SSL unsupported 

### ISSUE THREAD

**Issue by marmoure** [kentcdodds/react-fundamentals#239]
when trying to run on node 17 
```js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    ...
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
```
this seems to be a problem with open SSL as discussed here : https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
the [thread](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) provides a solution that works should we use that or completely drop support for Node V17

the workaround was to introduce `--openssl-legacy-provider` in `package.json`

i tired altering the scripts in `package.json` to 
```json
"scripts": {
    "start": "react-scripts --openssl-legacy-provider start",
    "build": "react-scripts --openssl-legacy-provider build",
    "test": "react-scripts --openssl-legacy-provider test --env=jsdom",
    "test:coverage": "npm --openssl-legacy-provider run test -- --watchAll=false",
    "test:exercises": "npm --openssl-legacy-provider run test -- testing.*exercises\\/ --onlyChanged",
    "setup": "node --openssl-legacy-provider setup",
    "lint": "eslint .",
    "format": "prettier --write \"./src\"",
    "validate": "npm-run-all --parallel build test:coverage lint"
  }
```
and everything works fine
Note this only works on node 17 if you switch to another version it will not work the result will be `node bad option: --openssl-legacy-provider`
how should we continue?

**Comment by kentcdodds** [comment]
Yeah, node 17 isn't supported by this workshop. You'll need to downgrade to a non-experimental version of node. Thanks!
