### ISSUE TITLE
setup failure

### ISSUE THREAD

**Issue by thorsten-istec** [kentcdodds/react-fundamentals#245]
Hello,
I can't run the setup successfully. The output is:

C:\Users\tq\epicreact>git --version
git version 2.34.1.windows.1

C:\Users\tq\epicreact>node --version
v14.18.0

C:\Users\tq\epicreact>npm --version
8.2.0

C:\Users\tq\epicreact>git clone https://github.com/kentcdodds/react-fundamentals.git
Cloning into 'react-fundamentals'...
remote: Enumerating objects: 1864, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 1864 (delta 9), reused 5 (delta 0), pack-reused 1843
Receiving objects: 100% (1864/1864), 3.30 MiB | 6.04 MiB/s, done.
Resolving deltas: 100% (1252/1252), done.

C:\Users\tq\epicreact>cd react-fundamentals

C:\Users\tq\epicreact\react-fundamentals>npm run setup --silent
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
    🚨  Failure: System Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.

C:\Users\tq\epicreact\react-fundamentals>npm run setup

> @kentcdodds/react-fundamentals@1.0.0 setup
> node setup

▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
    🚨  Failure: System Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.

C:\Users\tq\epicreact\react-fundamentals>npx --version
8.2.0

C:\Users\tq\epicreact\react-fundamentals>dir
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer:

 Verzeichnis von C:\Users\tq\epicreact\react-fundamentals

05.01.2022  14:48    <DIR>          .
05.01.2022  14:48    <DIR>          ..
05.01.2022  14:48            13.287 .all-contributorsrc
05.01.2022  14:48                28 .eslintignore
05.01.2022  14:48                19 .gitattributes
05.01.2022  14:48    <DIR>          .github
05.01.2022  14:48                67 .gitignore
05.01.2022  14:48                64 .npmrc
05.01.2022  14:48                28 .prettierignore
05.01.2022  14:48               401 .prettierrc
05.01.2022  14:48    <DIR>          .vscode
05.01.2022  14:48                75 CODE_OF_CONDUCT.md
05.01.2022  14:48             1.398 CONTRIBUTING.md
05.01.2022  14:48               112 docker-compose.yml
05.01.2022  14:48                96 Dockerfile
05.01.2022  14:48               247 LICENSE.md
05.01.2022  14:48           842.077 package-lock.json
05.01.2022  14:48             2.229 package.json
05.01.2022  14:48    <DIR>          public
05.01.2022  14:48            25.533 README.md
05.01.2022  14:48               110 sandbox.config.json
05.01.2022  14:48    <DIR>          scripts
05.01.2022  14:48                28 setup.js
05.01.2022  14:48    <DIR>          src
              17 Datei(en),        885.799 Bytes
               7 Verzeichnis(se), 91.258.961.920 Bytes frei

C:\Users\tq\epicreact\react-fundamentals>ver

Microsoft Windows [Version 10.0.19043.1288]

C:\Users\tq\epicreact\react-fundamentals>npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"

C:\Users\tq\epicreact\react-fundamentals>npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733"
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
    🚨  Failure: System Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.

**Comment by kentcdodds** [comment]
I'm afraid that output doesn't give us much useful information. Did you try the alternative setup instructions?

**Comment by thorsten-istec** [comment]
Thank you for your prompt reply. Where can I find the description of the alternative setup instructions?
I am currently using npm in the Windows Subsystem for Linux (WSL), which does work so far.

**Comment by kentcdodds** [comment]
It's all in the setup instructions in the README: https://github.com/kentcdodds/react-fundamentals#setup

**Comment by thorsten-istec** [comment]
npm install
npm run validate
has succeeded. Thanks a lot.
