### ISSUE TITLE
npm run setup failing

### ISSUE THREAD

**Issue by bdinesh** [kentcdodds/react-fundamentals#246]
Hi @kentcdodds 

When I run `npm run setup` after cloning the repo, I'm getting the below error.
Node: v14
npm: v6
OS: Windows 10

I understood that a temp script file is locked out and stopped the execution. Can you please help?

![image](https://user-images.githubusercontent.com/676802/148636221-7d18dcb2-a897-4508-82e6-3d3baa480160.png)

**Comment by kentcdodds** [comment]
Hi @bdinesh,

Hmm... Have you tried the alternative setup instructions listed in the README?

**Comment by bdinesh** [comment]
Hi @kentcdodds 

I'm able to run `npm install` and `npm run validate`. It's not a blocker, I'm able to run the web app and able to complete the exercises. 

Just wanted to check why `npm run setup` script is failing.

**Comment by howdyAnkit** [comment]
similarly, yarn was failing in initial because I use yarn most of the time. but then I did npm install. and saw a setup command seperate so had problem with that but after that upgraded my node which was 14 and updated to 16 LTS and then it worked fine for me

**Comment by kentcdodds** [comment]
I'm not sure why it's failing for you I'm afraid. Seems to work for most everyone else. Glad you got a workaround working though!
