### ISSUE TITLE
Setup failure

### ISSUE THREAD

**Issue by saimaparveen** [kentcdodds/react-fundamentals#247]
Hi, 

I am unable to setup successfully. Getting the following error:

**Versions:**
saimaparveen@Saimas-MacBook-Pro react-fundamentals % git --version
git version 2.24.3 (Apple Git-128)
saimaparveen@Saimas-MacBook-Pro react-fundamentals % node --version
v14.18.0
saimaparveen@Saimas-MacBook-Pro react-fundamentals % npm --version
6.14.15

**Error**

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-jest": "^26.6.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-jest was detected higher up in the tree:

  /Users/saimaparveen/node_modules/babel-jest (version: 27.4.5) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-jest" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /Users/saimaparveen/node_modules/babel-jest is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-jest in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-jest.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

Any idea how to get it working?

**Comment by kentcdodds** [comment]
You need to delete this folder: `/Users/saimaparveen/node_modules`

**Comment by kentcdodds** [comment]
Hope that helps! Cheers 😁
