### ISSUE TITLE
System Validation Issue

### ISSUE THREAD

**Issue by Rb-wahid** [kentcdodds/react-fundamentals#250]
when I was trying to install the repo, it gave me this error:

There were errors validating the compatibility of this computer:

    This computer has node@v17.4.0 installed, but node@12 || 14 || 15 || 16 is required. Please update node: https://nodejs.org

**Comment by kentcdodds** [comment]
Hi @Rb-wahid! 👋

You need to have one of the required versions of node installed. You have version 17.4.0 and that will not work with the workshop. Odd-numbered versions of node are unstable and you should use an even-numbered version. So you'll need to downgrade to v16 to go through this workshop.

Hope that helps! Good luck.

**Comment by Rb-wahid** [comment]
Thank you
