### ISSUE TITLE
Setup failure

### ISSUE THREAD

**Issue by fp-jcorriveau** [kentcdodds/react-fundamentals#251]
Windows 10
Terminal 1.11.3471.0
powershell 7.2.1

git version 2.35.1.windows.2
node v16.13.0
npm 8.1.0

It gives a success message but it actually does nothing.

![image](https://user-images.githubusercontent.com/53450693/155022091-1988dfe8-2009-44ea-93ed-d5a90d8773f7.png)

If I try npm install manually

![image](https://user-images.githubusercontent.com/53450693/155022460-2aa09a7c-a264-4544-8af1-15a8e0559bf7.png)

**Comment by fp-jcorriveau** [comment]
I did not manage to make it work properly on windows, then I tried using WSL Ubuntu.

After installing the prerequisites and VS Code Remote Development extension, it works perfectly.

**Comment by kentcdodds** [comment]
Sorry for the trouble. I'm glad you got it working. Unfortunately some packages just don't work very well on windows machines sometimes.
