### ISSUE TITLE
Screen freezing after hot reload

### ISSUE THREAD

**Issue by lucasheim** [kentcdodds/react-fundamentals#258]
I'm working through the first exercises, but whenever a make a change on the code, it reloads the exercise iframe, information is correct, but the page just freezes and I can't scroll or click on anything else. Only way out is refreshing the page.

There's an error on devtools:

![image](https://user-images.githubusercontent.com/13325346/166444375-d88ca86e-dc31-47b3-b332-665baef0dd97.png)

The same happens if I try to run in the isolated page, and I can't even select the text on the page, it's frozen.

![image](https://user-images.githubusercontent.com/13325346/166444551-a7d2c2a2-1bcc-48e8-847d-0001cdfe966e.png)

I had no issues with the setup and my specs are:

- MacOs Big Sur
- Chrome 100.0.4896.127
- Node 16.15.0
- npm 8.5.5

**Comment by lucasheim** [comment]
Seems like a problem with react-error-overlay: https://github.com/facebook/create-react-app/issues/11773

**Comment by lucasheim** [comment]
This workaround works: https://stackoverflow.com/a/70402397

**Comment by fitzage** [comment]
The Upgrading CRA step in the workaround introduced errors for me, probably because I'm at Node 14.something still. The second method didn't solve the problem.

**Comment by blacksandsolutions** [comment]
Upgrading CRA to 5 caused a bunch more issues I don't have time to debug right now.
Instead I downgraded to 4.03 as per https://stackoverflow.com/a/70602989/83542

**Comment by coofzilla** [comment]
> This workaround works: https://stackoverflow.com/a/70402397

I had to revert to CRA 4 as per steps 1-4 here. Is there an alternate solution so that we don't have to apply this fix for each workshop repo?

**Comment by kentcdodds** [comment]
I've figured out the issue and will be upgrading our version of create-react-app to v5 on all workshops in a moment.

**Comment by kentcdodds** [comment]
Ah, dang it. Ran into another snag. Will have to come back to this later.

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/1500684/168851478-3f5241c2-2047-4a45-af8b-06b41ff485db.png">

Follow my progress in #263 263

**Comment by fitzage** [comment]
What seems to be a suitable workaround for me is adding this override (currently in Node 16.15.0):

```
   "overrides": {
     "react-error-overlay": "6.0.9"
   }
 ```

**Comment by kentcdodds** [comment]
I just pushed a fix for this. Easiest way to update is to just run the setup all over again. If you want to keep your work around you could probably commit what you have and pull then run `node setup` again. It should work.

Here's what I did if you're curious: #263 

I'll get around to doing the same in the other repos soon hopefully (unless anyone else would like to do this 😄)
