### ISSUE TITLE
Errors while validating

### ISSUE THREAD

**Issue by alvarodelpazo** [kentcdodds/react-fundamentals#270]
Good morning! While trying to install and setup everything for the Epic React course, I've encountered some problems with the NodeJS version. While I have installed the latest node version (v18.3.0) the validation won't work correctly stating I have versión 17.7.1, when trying to uninstall said version, it pops that there's no such version installed. I have tried to solve this every way possible, uninstalled and installed node again but nothing seems to work.

alvarod@HPR23:~/Escritorio/Epic React/react-fundamentals$ node setup
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
There were errors validating the compatibility of this computer:

    This computer has node@v17.7.1 installed, but node@14 || 16 || 18 is required. Please update node: https://nodejs.org

If you would like to just ignore this error, then feel free to do so and install dependencies as you normally would in "/home/alvarod/Escritorio/Epic React/react-fundamentals". Just know that things may not work properly if you do...
    🚨  Failure: System Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.
alvarod@HPR23:~/Escritorio/Epic React/react-fundamentals$ node --version
v18.3.0

Thanks for any help! :)

**Comment by alvarodelpazo** [comment]
Hi once again, even downgrading to version 16 won't do the trick. 

![Captura de pantalla de 2022-06-03 11-05-55](https://user-images.githubusercontent.com/83280260/171824522-f3ee1606-c194-4cfc-86a2-44376c9b8a47.png)

**Comment by alvarodelpazo** [comment]
I even have proof that I don't have any version 17 installed in my computer...

![Captura de pantalla de 2022-06-03 11-34-31](https://user-images.githubusercontent.com/83280260/171829285-9d19f6ea-3e54-44d6-bece-9149c7fba3f9.png)

**Comment by kentcdodds** [comment]
It's possible your `npx` is set up with a different version of `node` that's not managed by `nvm`. Could you enter `which npx` and make sure it's where you expect it to be (relative to `which node`?)
