### ISSUE TITLE
Setup fails with error-> 'workshop-setup' is not recognized

### ISSUE THREAD

**Issue by rajat3085** [kentcdodds/react-fundamentals#272]
Below is the error - 

![image](https://user-images.githubusercontent.com/17711281/172873756-07071886-f48a-4032-a570-79caffb2ff4f.png)

If I take out the silent mode I get this error-

![image](https://user-images.githubusercontent.com/17711281/172874223-ccc37ddd-0fc1-4f19-9f30-91bf8445b1f5.png)

I have **npx 8.12.1** installed 

![image](https://user-images.githubusercontent.com/17711281/172874522-e3f9e997-7052-4de5-8179-06f5bbbc8b29.png)

Any help will be appreciated

**Comment by kentcdodds** [comment]
Looks like there's something wrong with the setup of `npm`, `node`, and `npx` on your machine. It's difficult for me to help you debug here. What do you get when you run `npm -v` and `node -v`?

**Comment by rajat3085** [comment]
> 

![image](https://user-images.githubusercontent.com/17711281/172876385-5a0da48c-a93f-4869-8cc7-47481abff916.png)

I see both npm and node installed with correct version

**Comment by rajat3085** [comment]
![image](https://user-images.githubusercontent.com/17711281/172876610-8340bd4a-206a-4010-8ced-76b1b3472d8a.png)

it gives the same error

**Comment by kentcdodds** [comment]
I'm afraid there's something strange with your system. The setup works for everyone else. I suggest trying one of the alternative approaches for completing the exercises. Check the README for more details.

**Comment by dashasalmiiarova** [comment]
I have the same error, just setting up the project on macbook pro m1pro chip it fails, while on intel everything worked fine. Maybe anyone have any suggestions?

**Comment by davit-b** [comment]
@dashasalmiiarova Yea, getting on M1Max MBP
```sh
~ react-fundamentals % node setup.js 
▶️  Starting workshop setup...
      Running the following command: npx "git://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git" -q
```

**Comment by davit-b** [comment]
Same with running the npx command itself
```sh
~ react-fundamentals % npx "git://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git" -q
sh: workshop-setup: command not found
```

**Comment by davit-b** [comment]
Here's an alternative - just run all the stuff the `setup.js` is doing manually.

```sh
// 1. system-validate part
node -v
    // make sure your node version is 14, 16 or 18.
npm -v 
    // make sure your npm version is >= 6

// 2.
npm install --legacy-peer-deps --no-save

// 3. 
npm run validate -s

// 4. Do autofill-email things
mkdir manual
cd manual
    // create two files, `package.json` and `autofill-feedback-email.js`. Copy paste the content from here https://gist.github.com/kentcdodds/2d44448a8997b9964b1be44cd294d1f5
    // Then execute them
npm install
cd ../ 
node manual/autofill-feedback-email.js
```

That should do it. Btw, this `setup.js` script is not really required. Maybe consider updating the Readme.md to state it's optional and can be done manually in the case it doesn't work? @kentcdodds

**Comment by dashasalmiiarova** [comment]
@davit-b thank you!
