### ISSUE TITLE
Missing Test Dependency - jest-watch-typeahead

### ISSUE THREAD

**Issue by Crazyloon** [kentcdodds/react-fundamentals#277]
Repro:

Create a clean folder.
Clone this repo's main branch
Run Setup
Run Test

Expectation: tests run

Actual Result: 
![image](https://user-images.githubusercontent.com/8146917/177057660-3150e63d-f1a3-4b82-93de-04d35fe52069.png)

Workaround: manually install jest-watch-typeahead 0.6.4 (or whichever latest version is compatible with CRA)

Potential Fix: add jest-watch-typeahead to the devDependencies in package.json

**Comment by kentcdodds** [comment]
Hi @Crazyloon, I was unable to reproduce this issue 😬

**Comment by Crazyloon** [comment]
Maybe you have something installed globally that I don't?

If there's additional info that may help, let me know. I searched jest-watch-typeahead on the discord, where someone else had the same error, so it's not completely isolated

**Comment by lstuartfry** [comment]
I also received this error. It looks like a compatibility issue with different versions of Node and react-scripts. Here is a related discussion on the create-react-app issues board - https://github.com/facebook/create-react-app/issues/11792.

**Comment by kentcdodds** [comment]
I think this has been resolved.
