### ISSUE TITLE
problem with npm run setup 

### ISSUE THREAD

**Issue by pedroSoaresll** [kentcdodds/react-fundamentals#279]
### Problem
After run `npm run setup`

![image](https://user-images.githubusercontent.com/11558773/177180746-3b15ca9b-6330-4a31-9204-d3c3b3d3ea3f.png)

> Note: after run `npm install` `npm run validate` `npm start`, I can get the application running normally so, I think I can continue normally the course. Just putting here the problem because would be something to fix.

### System:
![image](https://user-images.githubusercontent.com/11558773/177180920-3d38408f-224d-4b00-b788-b7518308bae2.png)
![image](https://user-images.githubusercontent.com/11558773/177180950-a4c952c8-c18e-4d3b-b147-e8364ae70fdf.png)
![image](https://user-images.githubusercontent.com/11558773/177180965-b613b3dc-1695-4c66-ae7d-c172e57c8b7e.png)
![image](https://user-images.githubusercontent.com/11558773/177181641-02b4e818-0a91-44ae-9802-a37f51b2f920.png)

**Comment by shawn-sandy** [comment]
> ### Problem
> After run `npm run setup`
> 
> ![image](https://user-images.githubusercontent.com/11558773/177180746-3b15ca9b-6330-4a31-9204-d3c3b3d3ea3f.png)
> 
> > Note: after run `npm install` `npm run validate` `npm start`, I can get the application running normally so, I think I can continue normally the course. Just putting here the problem because would be something to fix.
> 
> ### System:
> ![image](https://user-images.githubusercontent.com/11558773/177180920-3d38408f-224d-4b00-b788-b7518308bae2.png) ![image](https://user-images.githubusercontent.com/11558773/177180950-a4c952c8-c18e-4d3b-b147-e8364ae70fdf.png) ![image](https://user-images.githubusercontent.com/11558773/177180965-b613b3dc-1695-4c66-ae7d-c172e57c8b7e.png) ![image](https://user-images.githubusercontent.com/11558773/177181641-02b4e818-0a91-44ae-9802-a37f51b2f920.png)

Same issue

**Comment by smasinde** [comment]
Same..
git 2.36.1
npm 8.12.0
node 16.15.1
macos 12.4

**Comment by kentcdodds** [comment]
I've opened up an issue on npm about this: https://github.com/npm/cli/issues/5132

**Comment by kave-me** [comment]
I had the same issue, my node version is `v17.9.1`, just downgraded to `14` using [nvm](https://github.com/nvm-sh/nvm) (`nvm use 14`) and it worked just fine.

**Comment by kentcdodds** [comment]
This should be fixed with the latest version of npm 👍 

Thanks for your patience.

**Comment by carneiroDotDev** [comment]
Same here node v16.17.1 and npm 8.15.0
