### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ismaelmkumbi** [kentcdodds/react-fundamentals#280]
message from terminal:    ```
   Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
'workshop-setup' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by reeceosborn-toast** [comment]
I run into the same exact issue

**Comment by smasinde** [comment]
I'm getting something similar:
`  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
sh: workshop-setup: command not found`

**Comment by kentcdodds** [comment]
Duplicate of #279
