### ISSUE TITLE
Starting workshop -- errors out

### ISSUE THREAD

**Issue by bradamr** [kentcdodds/react-fundamentals#285]
Command output to node setup:

➜  react-fundamentals git:(main) node setup
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
sh: workshop-setup: command not found

**Comment by kentcdodds** [comment]
Hi Bradley,
This is a known issue I'm afraid #279. It's a bug in `npm`. I'm hoping it will be fixed soon. Until then you can follow the alternative setup instructions in the README.
