### ISSUE TITLE
workshop error set up - "workshop-setup: command not found"

### ISSUE THREAD

**Issue by noam-ackerman** [kentcdodds/react-fundamentals#287]
Hello, 
I'm trying to clone the repository and install it all step by step as written. 
after [i forked the original repository](https://github.com/noam-ackerman/react-fundamentals) as recommended i tried to install it via the terminal as instructed , but it stops at the "Starting workshop setup..." stage as bellow : 

`noamackerman@Noams-MBP-2 ~ %  cd documents/github/epic-react 
noamackerman@Noams-MBP-2 epic-react % git clone https://github.com/noam-ackerman/react-fundamentals.git
cd react-fundamentals
node setup
Cloning into 'react-fundamentals'...
remote: Enumerating objects: 1849, done.
remote: Total 1849 (delta 0), reused 0 (delta 0), pack-reused 1849
Receiving objects: 100% (1849/1849), 3.65 MiB | 2.29 MiB/s, done.
Resolving deltas: 100% (1279/1279), done.
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
/var/folders/83/x06wj56962d931vnhhvym1sh0000gn/T/npx-73ce3b2e.sh: line 1: workshop-setup: command not found
`

i've set for hours trying to figure it out, tried to adjust the path in the scripts/setup.js file  as recommended in some comments in [ this issue ](https://github.com/kentcdodds/react-fundamentals/issues/27) but it does't seem to solve the problem , also the error is different so i'm not sure it's related.  i don't know what to do or how to start the course already since i've been stuck on it ALL day with no progression. 
i have all the necessary versions for node, npx and git - see bellow:
`noamackerman@Noams-MBP-2 react-fundamentals % node -v
v18.7.0
noamackerman@Noams-MBP-2 react-fundamentals % npx -v
8.15.1
noamackerman@Noams-MBP-2 react-fundamentals % git -v
git version 2.37.1
`

node, npx and git been installed with Homebrew 
see bellow:
`noamackerman@Noams-MBP-2 react-fundamentals % which node
/opt/homebrew/bin/node
noamackerman@Noams-MBP-2 react-fundamentals % which npx
/opt/homebrew/bin/npx
noamackerman@Noams-MBP-2 react-fundamentals % which git
/opt/homebrew/bin/git
`

and I am using MacBook Pro (13-inch, M1, 2020) , with macOS MONTEREY version 12.4 with apple m1. 

please help me i want to start the course already and i tried anything i could think of in order to solve it :( 

thanks,
Noam

**Comment by lucabezerra** [comment]
To whomever else hits this problem, downgrading to npm 6 didn't do it for me (I needed to also downgrade Node to 14, but it still told me that something required npm to be >= 8). Following the secondary instructions in the README (running `npm install && npm run validate`) allowed me to pass through, although it didn't run the script itself, but it should be ok :)
