### ISSUE TITLE
Project not validating with Node LTS 16.16.0

### ISSUE THREAD

**Issue by smaestri** [kentcdodds/react-fundamentals#289]
Hi, I have Node LTS (Node 16.16.0 and NPM in 8.11.0) installed, and I have the following issue during `node setup`
 `This computer has npm@6.14.17 installed, but npm@>=8.16.0 is required. Please update npm by running npm install --global npm@>=8.16.0.`

Same probleme on the CI [here](https://github.com/kentcdodds/react-fundamentals/runs/7700410043?check_suite_focus=true)

I think it is due to [this last commit ](https://github.com/kentcdodds/react-fundamentals/commit/c0a23cf39faeb638c75c00d14d3bf8919082392b)10 days ago. Would it be possible to revert it @kentcdodds ? 
I force the installation for now.

Thank you in advance,

Regards,

Sylvain Maestri

**Comment by kentcdodds** [comment]
It's there a reason you can't update your version of npm as explained in the error message? Your version of npm is quite old.

**Comment by smaestri** [comment]
Thanx for your reply. OK I will use a newer version of NPM (allthough `8.1.0` seems not very old, from [25th of May 2022,](https://github.com/npm/cli/releases/tag/v8.11.0)?  Moreover, this version version is shipped with Node LTS, so I guess a lot of people will use this version.

As a side note, in the main documentation, in the [system requirements](https://github.com/kentcdodds/react-fundamentals#system-requirements), it is indicated  we can use NPM 6+, maybe you can set 8.16.0 instead.
THank you,

Regards,

Sylvain

**Comment by briantuju** [comment]
@smaestri As you mentioned, your npm version is `8.11.0`, but the script requires npm version `>=8.16.0`, you can check the `package.json` of the this repo.

![Screenshot from 2022-08-17 21-40-15](https://user-images.githubusercontent.com/69858377/185218121-4c42ddb0-2013-4b9b-b694-1f3be661eea7.png)

You can upgrade your npm using the command: `npm i -g npm@8.17.0`. This version is the latest as of this writing

**Comment by kentcdodds** [comment]
@smaestri, there are bugs in versions of npm older than 8.16.0 that we need fixed for people to go through this workshop effectively, that's why we need the latest version.

**Comment by smaestri** [comment]
OK thanx you for your replies. I have installed tatest NPM version (`8.18.0)`, working fine, so I close this issue. I would suggest to update [main documentation](https://github.com/kentcdodds/react-fundamentals#system-requirements) to avoid any confusion.
