### ISSUE TITLE
Cannot run git clone

### ISSUE THREAD

**Issue by GTierra2000** [kentcdodds/react-fundamentals#291]
gabrieltierra@macbook-pro react-fundamentals % git clone https://github.com/kentcdodds/react-fundamentals.git
cd react-fundamentals
node setup
Cloning into 'react-fundamentals'...
remote: Enumerating objects: 2025, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 2025 (delta 12), reused 25 (delta 6), pack-reused 1989
Receiving objects: 100% (2025/2025), 4.13 MiB | 6.54 MiB/s, done.
Resolving deltas: 100% (1366/1366), done.
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
/var/folders/45/32dhtbln5nj_yvmrryvkb6jc0000gn/T/npx-ccf78eda.sh: line 1: workshop-setup: command not found
gabrieltierra@macbook-pro react-fundamentals %

**Comment by kentcdodds** [comment]
Hi @GTierra2000,

What version of npm are you using? You should be on version 8.18.0 or greater. Otherwise you will experience this issue.

**Comment by GTierra2000** [comment]
Im on 8.15 but I’m not sure how to update. I’ve tried
Sudo npm update but then i get this:
I’ve been trying to solve this issue for a while I hope it’s a simple fix!
Im on an m1pro MacBook Pro

**Comment by kentcdodds** [comment]
The usual way to update `npm` is via `npm`:

```
npm install --global npm
```

**Comment by GTierra2000** [comment]
I tried running once without sudo and the other with it and was prompted
with this

**Comment by GTierra2000** [comment]
Got it to work with


sudo npm install -g ***@***.***


All good thank you for Reaching out as fast as you did! Looking
forward to the course!

**Comment by kentcdodds** [comment]
Sure thing! Enjoy 🙂
