### ISSUE TITLE
Local Host not reflecting changes

### ISSUE THREAD

**Issue by GTierra2000** [kentcdodds/react-fundamentals#292]
As I follow the course, my code doesn’t show any output in the opener browser from “npm start”. Any advice?
![EBCE42C6-6169-4F08-BF2E-A119EA284430](https://user-images.githubusercontent.com/102828602/185769208-14f39c4f-2dab-461d-abe7-c05e4eba4667.jpeg)
![BE305F97-1F97-4CF0-B582-BC9ABA9678F1](https://user-images.githubusercontent.com/102828602/185769210-441686b3-1794-4f7d-bea9-79c3a5981dd5.jpeg)

**Comment by kentcdodds** [comment]
Hi @GTierra2000, I can't tell from your photos whether you've actually completed the exercise. If you'd like to bring this to office hours we can work through it together: https://kcd.im/office-hours

**Comment by 3r1k0n** [comment]
@GTierra2000 are you using Windows subsystem for Linux (WSL)?
