### ISSUE TITLE
difference between running by docker vs running by npm run start?

### ISSUE THREAD

**Issue by mau2099** [kentcdodds/react-fundamentals#293]
hey kent!
course is awesome, I noticed we could build a docker image, but as in the title
is there difference between running by docker vs running by npm run start? could you point me to a blogpost?

**Comment by kentcdodds** [comment]
If you can run it without docker, then do so. I'm afraid I'm not sure of the best blog post to point you to for explaining what Docker does for you, but you could probably find some good resources pretty easily.
