### ISSUE TITLE
Getting npx is not available when it is.

### ISSUE THREAD

**Issue by bb-centrum** [kentcdodds/react-fundamentals#296]
Hi

I have just tried running the setup script and I get the following error.
```
D:\EpicReact\react-fundamentals>node setup
▶️  Starting workshop setup...
🚨  npx is not available on this computer. Please install npm@5.2.0 or greater
```
However I have npx installed. Confirmed by running the following:
```
D:\EpicReact\react-fundamentals>npx --version
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.19.2
```
So I edited `scripts/setup.js` and commented out lines 19 to 28 and ran the install script again. This time it ran fine. So looking at the logic in `setup.js` it's erroring out due to the npm WARN error I am receiving.

**Comment by kentcdodds** [comment]
I'm hopeful that this has been resolved with the latest version of the repo.
