### ISSUE TITLE
Emojis not showing

### ISSUE THREAD

**Issue by tfunq** [kentcdodds/react-fundamentals#297]
When cloning (or forking and cloning) the repository,  the emojis are not showing in the files. An example from README.md:

```
### Helpful Emoji 🐨 💰 💯 📝 🦉 📜 💣 💪 🏁 👨‍💼 🚨
```

**Comment by kentcdodds** [comment]
I've not had anyone else complain about this. Let me know if you still are having challenges with this. Please provide more details.
