### ISSUE TITLE
Alfred the Alert not appearing on failing tests

### ISSUE THREAD

**Issue by jcat4** [kentcdodds/react-fundamentals#298]
When I run a failing test, I expect to see Alfred the Alert 🚨, but I see nothing.

<img width="372" alt="Screen Shot 2022-10-09 at 3 12 40 PM" src="https://user-images.githubusercontent.com/7866287/194775300-bf1b4452-14a4-423b-867a-5dbaf08af949.png">

I did some debugging, and it looks like it's due to [this line of code](https://github.com/kentcdodds/react-workshop-app/blob/main/src/test-utils.tsx#L23): `error.stack = ''`.

On my machine, the `error`'s `message` is not being shown, just the `stack`.

```javascript
  const errorTest = new Error();
  errorTest.stack = "the stack";
  errorTest.message = "the message";

  throw errorTest;
```

<img width="314" alt="Screen Shot 2022-10-09 at 3 15 32 PM" src="https://user-images.githubusercontent.com/7866287/194775405-a2d27fc5-ca71-458f-8897-95935ffac185.png">

Because of this, setting `error.stack = ''` is effectively erasing the error from my terminal. For now, I've patched it by setting `error.stack = errror.message`. ([fork commit here](https://github.com/jcat4/react-workshop-app/commit/c9e3458607218a734e6c5b58321a6a52207001e9))
 
 Is this a setting on my end I can change, or a bug in the helper code? I'm willing to put in a PR if this is a bug!

**Comment by kentcdodds** [comment]
A PR would be welcome. I'm unsure why the behavior changed, but let's get it fixed. Thanks!

**Comment by pm0u** [comment]
I just had this issue today in the `react-fundamentals` repository. It looks like in package-lock.json the `react-workshop-app` is defined at version `6.0.1` so I think it is not installing the fixed version of this package.

**Comment by kentcdodds** [comment]
@pm0u, fixed. Thanks!
