### ISSUE TITLE
Unable to install workshop setup

### ISSUE THREAD

**Issue by sizzshiv-agarwal** [kentcdodds/react-fundamentals#306]
git clone https://github.com/kentcdodds/react-fundamentals.git
cd react-fundamentals
npm run setup --silent
Cloning into 'react-fundamentals'...
remote: Enumerating objects: 2044, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 2044 (delta 8), reused 11 (delta 5), pack-reused 2025
Receiving objects: 100% (2044/2044), 4.15 MiB | 7.70 MiB/s, done.
Resolving deltas: 100% (1372/1372), done.
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
/var/folders/33/bkx4kd090055r_6snv7xck1w0000gn/T/npx-61d6f001.sh: line 1: workshop-setup: command not found

**Comment by kentcdodds** [comment]
Hi!

You need to upgrade to the latest version of npm. The version you have has a bug that causes this issue.
