### ISSUE TITLE
Suggestion: Add a "pause shuffle" button to exercise #7 bonus demo

### ISSUE THREAD

**Issue by jgorfine-zendesk** [kentcdodds/react-fundamentals#321]
Hi @kentcdodds — my name's Jen, and I just finished taking the React Fundamentals course. 🙂

After engaging with the [exercise 7 bonus demo](https://react-fundamentals.netlify.app/isolated/final/07.extra-1.js) for a few minutes, I started to feel nauseated. I imagine that other folks may have had/will have a similar experience.

With that in mind, would it be possible to add some kind of "pause motion" button to that page? It certainly would help make the demo more accessible, per WCAG 2.1 ([Success Criterion 2.2.2](https://www.w3.org/TR/WCAG21/#pause-stop-hide)). I'd be more than happy to contribute this feature myself.

Thanks!

**Comment by kentcdodds** [comment]
Hi Jen! Thanks for the idea. I think that's a great idea. So a checkbox for "auto-shuffle" and button for "shuffle" so people can shuffle it when they want. The one thing you don't get out of that is you lose the ability to focus on one of the inputs and watch the focus follow or not follow the input if you click the button, but that's what the checkbox is for.

I would prefer the default is that it auto-shuffles though.

Thanks again for the idea, I'd welcome a pull request for this.

**Comment by kentcdodds** [comment]
Great idea. We should probably do a visible label. First rule of aria is to not use aria 😉 I'd rather not introduce people to aria unnecessarily when a regular label can be used. We can just call them "Input 1" "Input 2" etc.

**Comment by jgorfine-zendesk** [comment]
Sounds great! Should I include the labels in the same PR as the auto-shuffle checkbox, or would you prefer them to be in their own PR?

**Comment by kentcdodds** [comment]
All in one would probably be easier for both of us :)

**Comment by kentcdodds** [comment]
Finished. Thanks a lot @jgorfine-zendesk!

**Comment by jgorfine-zendesk** [comment]
My pleasure, @kentcdodds! If I see other opportunities for a11y enhancements (or anything else), I'll be sure to let you know. 😄

**Comment by kentcdodds** [comment]
Thanks!
