### ISSUE TITLE
Unable to access the website in firefox

### ISSUE THREAD

**Issue by Cloud-r** [kentcdodds/react-fundamentals#334]
Getting the following error when trying to access https://epicreact.dev/learn

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20Request%20failed%20with%20status%20code%20403&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
``` 
Noticed this network call  `https://app.egghead.io/api/v1/sellable_purchases/prices` fail with 403. Not sure if it is related
Tried with adblock off, still the same issue

**Comment by kentcdodds** [comment]
Hi @Cloud-r,

Unfortunately there's nothing we can do to solve this in this issue tracker. Could you please contact support with as many details as you can? team@epicreact.dev
