### ISSUE TITLE
Problem setting up

### ISSUE THREAD

**Issue by psiddharthdesign** [kentcdodds/react-fundamentals#335]
Hey Kent , 

I'm facing few issues with setting up react fundamentals. My node, git and npm are up to date. Pasted the errors I got below :

1. Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.

2. stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

3. Failure: Dependency Installation.

**Comment by kentcdodds** [comment]
That first error is the issue. Here's what ChatGPT said when I asked it how to solve this error:

---

This error indicates that there are files in the cache folder that are owned by the root user, which could cause permission issues when using npm.

To solve this error, you can follow these steps:

Open your terminal and navigate to the directory where the cache folder is located.

Run the following command to change the ownership of the cache folder to your current user:

```bash
sudo chown -R $(whoami) ~/.npm
```

This command will recursively change the ownership of all files and folders in the ~/.npm directory to your current user.

After the ownership has been changed, you can clear the npm cache by running the following command:

```bash
npm cache clean --force
```

This will remove all cached packages and their associated data.

Finally, you can try running the command that caused the error again to see if the issue has been resolved.
If you still encounter the same error, you may need to completely uninstall and reinstall npm to resolve the issue.

---

I then asked it for the windows solution in case you're on a windows machine:

---

Sure, here's how to solve this error on a Windows machine:

Open a command prompt or PowerShell as an administrator.

Run the following command to change the ownership of the cache folder to your user:

```bash
takeown /f "%AppData%\npm-cache" /r /d y
```
This command will change the ownership of the npm cache folder to your user account.

After changing the ownership, you can clear the npm cache by running the following command:
```bash
npm cache clean --force
```
This will remove all cached packages and their associated data.

Finally, you can try running the command that caused the error again to see if the issue has been resolved.
If you still encounter the same error, you may need to completely uninstall and reinstall npm to resolve the issue.

---

If that doesn't solve it, I suggest asking ChatGPT follow-up questions. In any case, it definitely seems like there's an issue on your local machine.
