### ISSUE TITLE
Hot Reload Not Working

### ISSUE THREAD

**Issue by angad11121** [kentcdodds/react-fundamentals#349]
It seems that the hot reload is not working, causing me to reload the app with "npm start" every time I edit, which takes around 40-60 seconds.

![image](https://github.com/kentcdodds/react-fundamentals/assets/50276105/095a9e08-6a42-4ff6-8e4e-f17d8e32c55e)
The image shows an older version of code (Exercise 1) in the DevTools.

![image](https://github.com/kentcdodds/react-fundamentals/assets/50276105/27ca0325-25e9-47d2-b890-e17eee938750)
Whereas this is the edited code.

I have checked the system, and project validation is fine. Any Ideas as to what the issue might be?

Thank You!
--------
### Edit 1:
I am getting a Webpack depreciation warning

(node:1937) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.

Could this be causing the issue?

--------
### Edit 2:
It seems that WSL was the one causing the issue. If anyone else is also facing the issue, you could edit the start script in package.json

From:
```js
"scripts": {
    "start": "craco start"
}
```

To:
```js
"scripts": {
    "start": "WATCHPACK_POLLING=true craco start"
}
```

If a more effective solution is available, please share it on this thread.

**Comment by kentcdodds** [comment]
Thanks for sharing the solution. We're working on an update to the material that will make this a non-issue in the future. Cheers!
