### ISSUE TITLE
@reach/tooltip error during installation

### ISSUE THREAD

**Issue by dmitrymar** [kentcdodds/react-fundamentals#351]
There appears to be an error with @reach/tooltip installation dependency

![Screenshot 2023-07-14 at 5 09 54 PM](https://github.com/kentcdodds/react-fundamentals/assets/1296629/4828a0bf-e5cb-4e02-812f-6490e6fd0e66)

My system:
Git: 2.41.0
NodeJs: 18.16.1
NPM: 9.7.2

I tried to install the package separately `npm i @reach/tooltip` as mentioned [here](https://www.npmjs.com/package/@reach/tooltip) but also getting an error.

![Screenshot 2023-07-14 at 5 19 17 PM](https://github.com/kentcdodds/react-fundamentals/assets/1296629/905de10a-b791-4656-a31b-20e1cdf0e030)

Please advise. Thanks!

**Comment by kentcdodds** [comment]
I believe npm was/is down. Could you try again later and let me know?

**Comment by dmitrymar** [comment]
I tried again and installation was successful. Thanks for the tip!
