### ISSUE TITLE
Feeback form link not clickable in Firefox

### ISSUE THREAD

**Issue by dcgoodwin2112** [kentcdodds/react-fundamentals#44]
The Feedback form link at the bottom of the exercise pages does not appear to be clickable in Firefox. It looks like the Workshop DevTools button may be overlaying the clickable area for the link. If I remove the Workshop DevTools  div from the DOM, then the link works as expected.

I'm using Firefox v81.0 on macOS 10.15.6

Thanks!
-Dan

**Comment by JacobMGEvans** [comment]
Good catch! Myself or someone else will take a look at this. 

You may also feel free to create a PR if you find a good solution as well 😄

**Comment by dcgoodwin2112** [comment]
Sounds great, thanks! I'll try to play around with this one a little later this evening.

**Comment by kentcdodds** [comment]
I've got it fixed :) Thanks!

**Comment by dcgoodwin2112** [comment]
Confirming the issue was resolved after updating to the latest version. Thanks, @kentcdodds and @JacobMGEvans!

**Comment by kentcdodds** [comment]
@all-contributors please add @dcgoodwin2112 for bugs
