### ISSUE TITLE
Exercise 1 - Use single append call

### ISSUE THREAD

**Issue by vernonk** [kentcdodds/react-fundamentals#46]
Not a huge deal at all, but just the idea of "fundamentals" made me think it would perhaps be valuable to use a single `append` call when doing the root extra credit work by using `appendChild` to add the "Hello World" `div` to it before appending to the DOM. 

Something like...

```
<script type="module">
      const root = document.createElement('div');
      root.setAttribute('id', 'root');
      const div = document.createElement('div');
      div.textContent = 'Hello World';
      div.classList.add('container');
      root.appendChild(div);
      document.body.append(root);
</script>
```

**Comment by kentcdodds** [comment]
Thanks for the feedback @vernonk. I'm not sure I understand what you're suggesting (or how what you're suggesting would make this any more "fundamental"). It seems like you simply found "another way to do it" which is great! Are you suggesting it's better for some reason?

**Comment by vernonk** [comment]
Thanks @kentcdodds. I was thinking that a single append to the DOM was better from a fundamental performance perspective to limit recalculating, painting, and layout for every single DOM element appended. I can see how that really isn't the "point" of the exercise, it just felt like possibly a good opportunity to reinforce a good practice. You're right though, it's definitely "another way to do it".

**Comment by kentcdodds** [comment]
99% of the people taking this workshop won't run into performance problems because they're appending nodes wrong. Most probably won't ever manually append nodes. I'm not worried about leading people astray here. Thanks though! :)
