### ISSUE TITLE
Can't watch video due to being in the exact country for which I bought the subscription

### ISSUE THREAD

**Issue by brunocalmels** [kentcdodds/react-fundamentals#5]
See screenshot: 
![image](https://github.com/kentcdodds/react-fundamentals/assets/8678464/abb787eb-2971-4acc-92bf-355a48da5757)

This doesn't always happen. Other times, it just reproduces audio and the video is stuck in the first frame. Most of the times it works well, anyway. Refreshing the page fixes it most of the times.

**Comment by kentcdodds** [comment]
Could you email support? team@epicreact.dev

Sorry for the trouble.

**Comment by brunocalmels** [comment]
Sure!
