### ISSUE TITLE
Enable to starting workshop setup...

### ISSUE THREAD

**Issue by FedericaZuccarello** [kentcdodds/react-fundamentals#55]
Git: 2.28.0.windows.1
Node: v12.18.4
npm: 6.14.6

1.  git clone https://github.com/kentcdodds/react-fundamentals.git
2. cd react-fundamentals
3. npm run setup --silent         made this error:
**Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
Error: EPERM: operation not permitted, mkdir 'C:\Users\Federica'
command not find: bb452ffe53a5caa3600197e1d8005733**

I tried to reinstall git and node.js and to execute the command **npx git://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git** as recommended in a thread, but doesn't work.
Can someone help me, please?

UPDATE 1.
After running "npm cache clean" as admin, I retry to run "npm run setup --silent". The error now is:
 Starting workshop setup...
      **Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Zuccarello\AppData\Roaming\npm-cache\_npx\10108" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Federica Zuccarello\AppData\Roaming\npm-cache\_logs\2020-10-01T17_05_46_471Z-debug.log
Install for [ 'git+https://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git' ] failed with code 1**

[RESOLVED]
Problem was due to space in my user name FirstName LastName and issue is with npx. I applied following fix and everything worked just fine:
**npm config set cache C:\tmp\nodejs\npm-cache --global** (as admin)
than: 
**npm run setup --silent**

**Comment by kentcdodds** [comment]
Hi @FedericaZuccarello!

I'm glad you got this problem resolved. Thanks for following up :)

**Comment by FedericaZuccarello** [comment]
Thanks, I left it to help someone that will have my same problem.Il 1 ott 2020 22:08, "Kent C. Dodds" <notifications@github.com> ha scritto:
Hi @FedericaZuccarello!
I'm glad you got this problem resolved. Thanks for following up :)

**Comment by Nitin2392** [comment]
I had the same issue! Looks like `npx` has an issue with a space between FirstName and LastName atleast on Windows. 

Using the commands :

`npm config set cache C:\tmp\nodejs\npm-cache --global` (as admin)

followed by 

`npm run setup --silent`

fixed the issue
