### ISSUE TITLE
Can't access course with old email

### ISSUE THREAD

**Issue by 17hogeju** [kentcdodds/react-fundamentals#7]
Hi,
I purchased the Epic React course with my work email [julia.hoge@sentry.io](mailto:julia.hoge@sentry.io). I no longer have access to that email and would like my account to be under my personal email: [17hogeju@gmail.com](mailto:17hogeju@gmail.com).

I sent an email, but I suspect it was sent to spam since I sent it from my current email.

Please let me know if I can get assistance on this issue.

**Comment by kentcdodds** [comment]
Hi Julia!

So sorry for the trouble. The whole team was heads-down on the conference for the last week. I do see your email address in the team's inbox and they're slowly crawling through the support emails and should get to yours soon. Thanks for understanding!
