### ISSUE TITLE
npx error  npm-cache does not contain a package.json file.

### ISSUE THREAD

**Issue by ernestweems** [kentcdodds/react-fundamentals#74]
**On Windows 10 OS** 
v12.18.4
npm 6.14.6
npx 6.14.6
1.I have tried the suggested `npx git://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git` instead of the https://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git
2. deleting package-lock.json and npm install
3. uninstalling reinstalling node.js

```
 ernest weems@DESKTOP-LG366MO MINGW64 ~/Documents/Development/Github-Projects/epicreact/react-fundamentals (main)
$ npm run setup --silent
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
npm ERR! code ENOLOCAL
npm ERR! Could not install from "weems\AppData\Roaming\npm-cache\_npx\4880" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ernest weems\AppData\Roaming\npm-cache\_logs\2020-10-03T16_15_57_058Z-debug.log
Install for [ 'git+https://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git' ] failed with code 1
```

Any one have fix for this error ?

**Comment by kentcdodds** [comment]
Hi @ernestweems!

It appears that you may have a bad npm cache. Try running `npm cache clear` and then try again.

**Comment by ernestweems** [comment]
@kentcdodds 
npx error npm-cache package.json issues resolved.
Now I get the following:
Install for [ 'git+https://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git' ] failed with code 1

I tried the solutions from other post like the following but not working is there alternative to get this working? Any help is appreciated!!
```
npx https://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git
```
and
```
 npx git://gist.github.com/bb452ffe53a5caa3600197e1d8005733.git
```

**Comment by ernestweems** [comment]
Let me summarize how I fixed install issues.

First NPM does not recommend using ` npm cache clean`

If you use `npm cache clean --force`

you might get and warning like this:

npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be 
valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one

NPX has known issues with name paths with spaces and in them like mine `ernest weems@DESKTOP-LG366MO MINGW64` so I updated by removing the space from my user name path to `ernestweems@DESKTOP-LG366MO MINGW64` . There is also another way and is to use short path name for you folder by using the CMD and navigating to the User folder and use command `dir /x` you will get back list of user name short paths something like this `FOLDERNAME~1` then take this and use that in the environment variable folder path instead of your folder name with space in it. Removing the space resolved the NPX errors.

Now NPX errors are gone I got the following:
17 error C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found

So what resolved this was to add go into my environment variables PATH and the following(Note I did not change any existing paths just added the paths below):
C:\Program Files\Git\usr\bin
C:\Program Files\Git\mingw64\libexec\git-core

credit this to: [How to fix “git-sh-setup: file not found” in windows?
](https://stackoverflow.com/questions/49256190/how-to-fix-git-sh-setup-file-not-found-in-windows) 

I did restart and ran install command `npm run setup --silent` and all went well with no issues! Hope this can help others. Thanks @kentcdodds for responding!

**Comment by ernestweems** [comment]
@kentcdodds closing this issue  all good now!

**Comment by kentcdodds** [comment]
Thanks for the info @ernestweems!
