### ISSUE TITLE
Reference Error:  expect is not defined

### ISSUE THREAD

**Issue by erikbcox** [kentcdodds/react-fundamentals#75]
Windows 10
git 2.22.0.windows.1
node 10.13.0
npm 6.14.6

Site runs but issue running tests. Wiped the folder and got the same issue on the second try as well.

C:\Source\Learn\EpicReact\react-fundamentals>npm run setup --silent
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
npx: installed 1 in 7.863s
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
npx: installed 2 in 6.96s
    ✅  Success: System Validation

    ▶️  Starting: Dependency Installation
          Installing third party code dependencies so the workshop works properly on this computer.
          Running the following command: npm install
husky > Setting up git hooks
husky > Done
added 2246 packages from 852 contributors and audited 2256 packages in 42.936s

170 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

    ✅  Success: Dependency Installation

    ▶️  Starting: Project Validation
          Running validation checks to ensure dependencies were installed properly
          Running the following command: npm run validate -s

(node:17544) ExperimentalWarning: The fs.promises API is experimental
(node:4884) ExperimentalWarning: The fs.promises API is experimental
(node:14452) ExperimentalWarning: The fs.promises API is experimental
(node:16932) ExperimentalWarning: The fs.promises API is experimental
(node:17640) ExperimentalWarning: The fs.promises API is experimental
 FAIL  src/__tests__/06.extra-2.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

 FAIL  src/__tests__/05.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

 FAIL  src/__tests__/06.extra-3.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

 FAIL  src/__tests__/07.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

 FAIL  src/__tests__/06.js
  ● Test suite failed to run

    ReferenceError: expect is not defined

      at Object.<anonymous> (node_modules/@testing-library/jest-dom/dist/extend-expect.js:7:1)
      at Object.<anonymous> (node_modules/@testing-library/jest-dom/extend-expect.js:2:1)

Test Suites: 5 failed, 5 total
Tests:       0 total
Snapshots:   0 total
Time:        5.546 s
Ran all test suites.
    🚨  Failure: Project Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.

Curious if it was related to something installed globally. Nothing jumped out at me.

C:\Source\Learn\EpicReact\react-fundamentals>npm list -g --depth 0
C:\Users\erik.cox\AppData\Roaming\npm
+-- @ionic/cli@6.10.1
+-- @vue/cli@3.0.3
+-- @vue/cli-plugin-typescript@3.0.3
+-- cordova@9.0.0
+-- cordova-res@0.15.1
+-- create-react-app@2.1.8
+-- cross-env@5.2.0
+-- eslint@6.0.1
+-- expo-cli@3.25.1
+-- firebase-tools@8.5.0
+-- gatsby-cli@2.5.4
+-- native-run@0.3.0
+-- npm@6.14.6
+-- UNMET PEER DEPENDENCY react@16.8.4
+-- react-devtools@3.6.1
+-- react-native@0.59.9
+-- serve@11.0.0
+-- tslint@5.11.0
+-- tslint-react@3.6.0
+-- typescript@3.1.3
`-- yarn@1.16.0

npm ERR! peer dep missing: react@16.8.3, required by react-native@0.59.9
npm ERR! peer dep missing: webpack@^2.3.0 || ^3.0.0 || ^4.0.0, required by fork-ts-checker-webpack-plugin@0.4.9
npm ERR! peer dep missing: react-refresh@^0.8.2, required by @pmmmwh/react-refresh-webpack-plugin@0.3.3

**Comment by kentcdodds** [comment]
Hi @erikbcox,

Nothing jumps out at me either on this. One thing you might try is upgrading your version of node and trying over again. Otherwise, I'm not sure 😬

**Comment by erikbcox** [comment]
Updating Node fixed the issue! Really appreciate the quick reply!

Update node
C:\Source>node --version
v12.18.4

C:\Source>npm --version
6.14.6

 PASS  src/__tests__/06.extra-3.js
 PASS  src/__tests__/07.js
 PASS  src/__tests__/06.extra-2.js
 PASS  src/__tests__/05.js
 PASS  src/__tests__/06.js

Test Suites: 5 passed, 5 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        4.7 s, estimated 9 s
Ran all test suites.
