### ISSUE TITLE
Mac error command "node setup"

### ISSUE THREAD

**Issue by vietdan1613** [kentcdodds/react-fundamentals#8]
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q -- --no-autofill
npm ERR! code Unknown system error -86
npm ERR! syscall spawn
npm ERR! errno -86
npm ERR! spawn Unknown system error -86
npm ERR! code Unknown system error -86
npm ERR! syscall spawn
npm ERR! errno -86
npm ERR! spawn Unknown system error -86

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nguyenviet/.npm/_logs/2024-05-05T12_37_07_346Z-debug-0.log

**Comment by kentcdodds** [comment]
Hi. Could you give details on your system? What version of node and npm are you running?
