### ISSUE TITLE
Problem during install 

### ISSUE THREAD

**Issue by alexiscomte** [kentcdodds/react-fundamentals#88]
![image](https://user-images.githubusercontent.com/411638/95216815-cb58b300-07f2-11eb-99b5-ba5dd1ac755b.png)

Hi I have tried to install but I am getting stucked

Any Hint of what I should do ?

**Comment by kentcdodds** [comment]
Hi @alexiscomte,

Could you give this thread a look? https://github.com/kentcdodds/react-fundamentals/issues/27

A handful of people are having issues with setup and each seems to have a different solution.

**Comment by alexiscomte** [comment]
thank you, Yes I have seen the thread but this is not the same case as mine

I have removed all globally installed packages, I made reboot but still, I am stuck.  

I have no idea where to look now

**Comment by alexiscomte** [comment]
I have found out, I was using my external drive that had a FAT file system

https://npm.community/t/fat-file-system-drives-cause-npm-install-to-fail-if-packages-are-being-updated/4854

**Comment by kentcdodds** [comment]
Thanks for reporting back on this @alexiscomte! [I've made a note of this](https://docs.google.com/document/d/1OUYIaGsIGRpmaVuuaGKKhh-toHu_R4L-lMjjXbgerkE/edit#).
